// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Hanzi Hunt",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Hanzi Hunt",
            targets: ["AppModule"],
            bundleIdentifier: "com.lala.Hanzi-Hunt",
            teamIdentifier: "UR2GTWY975",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.pictureFolder, mode: .readWrite),
                .camera(purposeString: "Hanzi Hunt needs camera access to display Chinese characters on objects.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageModes: [.version("6")]
)
